version: "3.7"

services:
  database:
    container_name: xz_bot_db
    image: mongo
    #command: jekyll serve --watch --incremental
    ports:
    - "27017:27017"
    volumes:
    - xzbotmongo:/data/db

volumes:
  xzbotmongo: